### ISSUE TITLE
itunes!!!

### ISSUE THREAD

**Issue by PANOSPAP1982** [chrisdixon161/song-finder#1]
hello my friend!!!tell me please this is for searching music...songs and albums from itunes?and if yes,please could you make a web version?I am begging you!!!

**Comment by chrisdixon161** [comment]
Yes this is for searching music from itunes, this is already a web version!

**Comment by PANOSPAP1982** [comment]
woowwwwwwww....my good friend please because I have no idea from programming and developing can you release it?I am begging youuuuuuuuu man

**Comment by chrisdixon161** [comment]
The app is not intended to be released in its current form, it is a demo project for a training course I created. it would need a bit more polishing to be released publicly

**Comment by PANOSPAP1982** [comment]
wooo...my friend I love english and spanish music so much!!!please tell me something increase unlimited results for every song and album?if not because itunes appear more less 300 results can you as development increase unlimited results?I am searching one web where use api from itunes and increase unlimited results for many months!!!please man can you try it?

**Comment by PANOSPAP1982** [comment]
PLEASE MY FRIEND ANSWER ME MAN!!!

**Comment by chrisdixon161** [comment]
Please be patient I am busy working. I am not aware of a solution to increase this, this is set by Apple using the limit query.
I am going to close this as this area is reserved for issues, best of luck.

**Comment by chrisdixon161** [comment]
No issue with repository to fix
